# network architecture
model-module: espnet.nets.pytorch_backend.e2e_mt_transformer:E2E
# encoder related
etype: blstm     # encoder architecture type
elayers: 2
eunits: 512
eprojs: 512
subsample: "1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 2
dunits: 512
context-residual: true
# attention related
atype: add
adim: 512

# minibatch related
batch-size: 1
maxlen-in: 50  # if input length  > maxlen-in, batchsize is automatically reduced
maxlen-out: 50 # if output length > maxlen-out, batchsize is automatically reduced

# other config
dropout-rate: 0.3
dropout-rate-decoder: 0.3
lsm-weight: 0.1
weight-decay: 1e-6

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 20
patience: 3

# scheduled sampling option
sampling-probability: 0.0
num-save-attention: 3
